### ISSUE TITLE
Option to limit crystals/trees, while not limiting aura

### ISSUE THREAD

**Issue by thephoenixlodge** [TheCodex6824/AuraControl#1]
As per title, it would be great if there was the option to limit the crystals and trees without affecting the aura. In my case I'm looking to limit crystal gen to the betweenlands biomes, however I don't want to lock the player out of being able to do TC crafting in their overworld (skyblock) base

**Comment by TheCodex6824** [comment]
This should be easy enough to add for the next update.

**Comment by TheCodex6824** [comment]
The update with this feature should be [here](https://www.curseforge.com/minecraft/mc-mods/auracontrol/files/3013979) once it gets approved.

**Comment by thephoenixlodge** [comment]
awesome, thanks
